<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<IsPackable>true</IsPackable>
		<PackageVersion>1.0.0</PackageVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OrchardCore.Module.Targets" Version="2.2.1" />
		<PackageReference Include="Microsoft.Extensions.AI" Version="10.3.0" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
	</ItemGroup>

</Project>
